name: chess_pgn_parser
description: A starting point for Dart libraries or applications.
version: 0.1.0
repository: https://github.com/bencehornak/dart-chess-pgn-parser

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  antlr4: ^4.12.0
  chess: ^0.8.0
  logging: ^1.1.1
  meta: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
